<a href="https://colab.research.google.com/github/TamannnaK/Simulation-Lab/blob/main/82_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
d1 = 2  # last digit of student ID
d2 = 8  # second last digit of student ID

A = np.array([[d1 + 2, d2 + 1],
              [2 * d1, d2 + 2]])


print("Matrix A:")
print(A)

print("Shape of A:", A.shape)


Matrix A:
[[ 4  9]
 [ 4 10]]
Shape of A: (2, 2)


In [5]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)


Determinant of A: 4.0
Rank of A: 2


In [6]:

eigvals_A = np.linalg.eigvals(A)
print("Eigenvalues of A:", eigvals_A)

if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:")
    print(inv_A)
else:
    print("Matrix A is not invertible.")

Eigenvalues of A: [ 0.29179607 13.70820393]
Inverse of A:
[[ 2.5  -2.25]
 [-1.    1.  ]]


In [7]:
# Add +1 to element A[0,0]
B = A.copy()
B[0, 0] += 1

print("\nMatrix B (A[0,0] increased by +1):")
print(B)



Matrix B (A[0,0] increased by +1):
[[ 5  9]
 [ 4 10]]


In [8]:

print("Shape of B:", B.shape)

det_B = np.linalg.det(B)
print("Determinant of B:", det_B)

rank_B = np.linalg.matrix_rank(B)
print("Rank of B:", rank_B)

eigvals_B = np.linalg.eigvals(B)
print("Eigenvalues of B:", eigvals_B)

if det_B != 0:
    inv_B = np.linalg.inv(B)
    print("Inverse of B:")
    print(inv_B)
else:
    print("Matrix B is not invertible.")

Shape of B: (2, 2)
Determinant of B: 13.999999999999996
Rank of B: 2
Eigenvalues of B: [ 1. 14.]
Inverse of B:
[[ 0.71428571 -0.64285714]
 [-0.28571429  0.35714286]]
